---
- hosts: dockerhost
  tasks:
  - name: stop existing container
    command: docker stop regapp-server
    ignore_errors: yes

  - name: remove existing container
    command: docker rm regapp-server
    ignore_errors: yes

 -  name: remove existing image
    command: docker rmi regapp:latest
    ignore_errors: yes

  - name: run a container
    command: docker run -d --name regapp-server -p 8082:8080 chandru007/regapp:latest

